/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services.website-development'
import { Route as ServicesVideoCreationRouteImport } from './routes/services.video-creation'
import { Route as ServicesSocialMediaMarketingRouteImport } from './routes/services.social-media-marketing'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesPerformanceMarketingRouteImport } from './routes/services.performance-marketing'
import { Route as ServicesContentMarketingRouteImport } from './routes/services.content-marketing'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/services/website-development',
    path: '/services/website-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesVideoCreationRoute = ServicesVideoCreationRouteImport.update({
  id: '/services/video-creation',
  path: '/services/video-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialMediaMarketingRoute =
  ServicesSocialMediaMarketingRouteImport.update({
    id: '/services/social-media-marketing',
    path: '/services/social-media-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPerformanceMarketingRoute =
  ServicesPerformanceMarketingRouteImport.update({
    id: '/services/performance-marketing',
    path: '/services/performance-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesContentMarketingRoute =
  ServicesContentMarketingRouteImport.update({
    id: '/services/content-marketing',
    path: '/services/content-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/content-marketing': typeof ServicesContentMarketingRoute
  '/services/performance-marketing': typeof ServicesPerformanceMarketingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/video-creation': typeof ServicesVideoCreationRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/content-marketing': typeof ServicesContentMarketingRoute
  '/services/performance-marketing': typeof ServicesPerformanceMarketingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/video-creation': typeof ServicesVideoCreationRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/content-marketing': typeof ServicesContentMarketingRoute
  '/services/performance-marketing': typeof ServicesPerformanceMarketingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/video-creation': typeof ServicesVideoCreationRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/content-marketing'
    | '/services/performance-marketing'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/video-creation'
    | '/services/website-development'
    | '/admin/$id'
    | '/admin/new'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/content-marketing'
    | '/services/performance-marketing'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/video-creation'
    | '/services/website-development'
    | '/admin/$id'
    | '/admin/new'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/content-marketing'
    | '/services/performance-marketing'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/video-creation'
    | '/services/website-development'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesContentMarketingRoute: typeof ServicesContentMarketingRoute
  ServicesPerformanceMarketingRoute: typeof ServicesPerformanceMarketingRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesSocialMediaMarketingRoute: typeof ServicesSocialMediaMarketingRoute
  ServicesVideoCreationRoute: typeof ServicesVideoCreationRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/services/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/video-creation': {
      id: '/services/video-creation'
      path: '/services/video-creation'
      fullPath: '/services/video-creation'
      preLoaderRoute: typeof ServicesVideoCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-marketing': {
      id: '/services/social-media-marketing'
      path: '/services/social-media-marketing'
      fullPath: '/services/social-media-marketing'
      preLoaderRoute: typeof ServicesSocialMediaMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/performance-marketing': {
      id: '/services/performance-marketing'
      path: '/services/performance-marketing'
      fullPath: '/services/performance-marketing'
      preLoaderRoute: typeof ServicesPerformanceMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/content-marketing': {
      id: '/services/content-marketing'
      path: '/services/content-marketing'
      fullPath: '/services/content-marketing'
      preLoaderRoute: typeof ServicesContentMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesContentMarketingRoute: ServicesContentMarketingRoute,
  ServicesPerformanceMarketingRoute: ServicesPerformanceMarketingRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesSocialMediaMarketingRoute: ServicesSocialMediaMarketingRoute,
  ServicesVideoCreationRoute: ServicesVideoCreationRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
